version: "3"

services:
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: mrb-php
        volumes:
            - ./src:/var/www/html/
        ports:
            - "80:80"
            - "443:443"
        links:
            - db

    db:
        image: mysql:8.0
        container_name: mrb-mysql
        volumes:
            - /var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=teste
# Para liberar acesso do PHP ao mysql precise fazer o seguinte:
# docker container exec -it mrb-mysql bash
# mysql -u root -p
# ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
# ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
# ALTER USER 'default'@'%' IDENTIFIED WITH mysql_native_password BY 'secret';
